
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network
    environment:
      - NODE_ENV=production

  notekeeper:
    build:
      context: ./notekeeper
      dockerfile: notekeeper/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - FLASK_ENV=production
networks:
  app-network:
    driver: bridge
