services:
  - type: web
    name: my-flask-app
    env: python
    region: Frankfurt # or another region close to your users
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn __init__:app
    envVars:
      - key: SECRET_KEY
        value: "85cab4e486a7bbaecbaea9420447fe59"
      - key: DATABASE_URL
        value: "sqlite:///PVWebAppDB.db"
