services:
  - type: web
    name: my-flask-app
    env: python
    region: Frankfurt # or another region close to your users
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: SECRET_KEY
        value: "ENTER-KEY"
      - key: DATABASE_URL
        value: "sqlite:///PVWebAppDB.db"
